"""`freepod key`: the account's SSH keys, and which one this machine holds.

Registration is the one moment the client knows both halves of a pair, so it
is where the link between a registered public key and a local file is
recorded rather than guessed later. The edge answers every offered key with
"partial success", so a client that tries several exhausts `MaxAuthTries`
before reaching the right one — it must know which key to offer.
"""

from __future__ import annotations

import base64
import hashlib
import json
import os
import subprocess
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import DuplicateKey, FreepodError, UsageError
from .api import ApiClient
from .config import config_dir, ensure_config_dir
from .table import BLANK, format_time, render

COLUMNS = ("", "FINGERPRINT", "LABEL", "TYPE", "ADDED")

#: The client-generated key, per machine and shared across environments; which
#: of them it is *registered* on is what the record below keys by environment.
GENERATED_KEY_NAME = "id_ed25519"

RECORD_VERSION = 1



def ssh_dir() -> Path:
    """Where a user's own keys live. Read for recovery; never written to.

    Resolved per call, like `config_dir()`: binding it at import would freeze
    whatever `HOME` happened to be then.
    """
    return Path.home() / ".ssh"


def record_path() -> Path:
    """Where the local key record lives. Reading it must not create anything."""
    return config_dir() / "keys.json"


def generated_key_path() -> Path:
    return config_dir() / GENERATED_KEY_NAME


def generated_public_key() -> Path:
    return Path(str(generated_key_path()) + ".pub")


def fingerprint_for_line(line: str) -> Optional[str]:
    """`SHA256:...` for one OpenSSH public key line, or None if unreadable."""
    parts = line.strip().split()
    if len(parts) < 2:
        return None
    try:
        blob = base64.b64decode(parts[1], validate=True)
    except Exception:
        return None
    digest = hashlib.sha256(blob).digest()
    return "SHA256:" + base64.b64encode(digest).decode("ascii").rstrip("=")


def fingerprint_for_file(path: Path) -> Optional[str]:
    try:
        return fingerprint_for_line(path.read_text(encoding="utf-8"))
    except OSError:
        return None


# --------------------------------------------------------------------------
# The local record
# --------------------------------------------------------------------------


def load_record() -> dict:
    try:
        with open(record_path(), "r", encoding="utf-8") as handle:
            data = json.load(handle)
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def save_record(data: dict) -> None:
    """Write the record atomically at mode 0600, in a 0700 directory."""
    ensure_config_dir()
    path = record_path()
    temporary = f"{path}.{os.getpid()}.tmp"
    descriptor = os.open(temporary, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(data, handle, indent=2)
            handle.write("\n")
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise
    os.chmod(path, 0o600)


def local_key(env: str) -> Optional[Dict[str, str]]:
    """This machine's recorded key for one environment: fingerprint and path.

    Keyed by environment because an account on dev is not the account on prod;
    a key registered against one must never be offered as this machine's key
    for the other.
    """
    entry = load_record().get("environments", {}).get(env)
    if not isinstance(entry, dict):
        return None
    fingerprint = entry.get("fingerprint")
    path = entry.get("path")
    if not isinstance(fingerprint, str) or not isinstance(path, str):
        return None
    return {"fingerprint": fingerprint, "path": path}


def remember(env: str, fingerprint: str, path: Path) -> None:
    data = load_record()
    environments = data.setdefault("environments", {})
    environments[env] = {"fingerprint": fingerprint, "path": str(path)}
    data["version"] = RECORD_VERSION
    save_record(data)


def forget(env: str) -> None:
    data = load_record()
    environments = data.get("environments")
    if isinstance(environments, dict) and environments.pop(env, None) is not None:
        save_record(data)


# --------------------------------------------------------------------------
# Generation and reading
# --------------------------------------------------------------------------


def generate_keypair(path: Path) -> str:
    """Write an Ed25519 keypair at `path`, 0600, and return its public line.

    Generated by `ssh-keygen` rather than by a crypto library: it is already
    present wherever these keys will be used, it writes exactly the on-disk
    format OpenSSH expects, and it keeps the client's dependencies to the
    three it ships with.

    No passphrase: a prompt on every command that opens a connection is
    hostile to a tool meant to be scriptable. The mitigation is that the key
    is per machine and independently revocable — a user wanting a passphrase
    or a hardware token registers their own key instead.
    """
    ensure_config_dir()
    comment = f"freepod@{os.uname().nodename}" if hasattr(os, "uname") else "freepod"
    try:
        result = subprocess.run(
            ["ssh-keygen", "-t", "ed25519", "-N", "", "-C", comment, "-f", str(path)],
            capture_output=True,
            text=True,
        )
    except FileNotFoundError:
        raise FreepodError(
            "ssh-keygen was not found, so no key could be generated. Install "
            "OpenSSH, or register a key you already have with "
            "`freepod key add <path to .pub>`."
        ) from None
    if result.returncode != 0:
        raise FreepodError(
            f"ssh-keygen failed: {(result.stderr or result.stdout).strip()[:300]}"
        )

    os.chmod(path, 0o600)
    return Path(str(path) + ".pub").read_text(encoding="utf-8").strip()


def read_public_key(path: Path) -> str:
    """The public key line at `path`, refusing a private key file."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise UsageError(f"cannot read {path}: {exc}") from None

    if "PRIVATE KEY" in text:
        raise UsageError(
            f"{path} is a private key. Register the public half instead: "
            f"{path}.pub — and never share the private one."
        )
    if not fingerprint_for_line(text):
        raise UsageError(f"{path} is not an OpenSSH public key file")
    return text.strip()


# --------------------------------------------------------------------------
# Recovery
# --------------------------------------------------------------------------


def candidate_public_keys() -> List[Path]:
    """Public key files this machine offers, client-owned ones first.

    Public files, never private ones: a key held in an agent or on a hardware
    token has no private file at all, and `ssh -i <public key>` with
    `IdentitiesOnly=yes` is the documented way to select such an identity.
    """
    candidates: List[Path] = []
    generated = generated_public_key()
    if generated.is_file():
        candidates.append(generated)
    user_keys = ssh_dir()
    if user_keys.is_dir():
        candidates.extend(sorted(p for p in user_keys.glob("*.pub") if p.is_file()))
    return candidates


def recover(registered: List[dict]) -> List[Path]:
    """Local public key files whose fingerprint the account has registered."""
    known = {key.get("fingerprint") for key in registered}
    return [p for p in candidate_public_keys() if fingerprint_for_file(p) in known]


def _recorded_key(env: str, registered: List[dict]) -> Optional[Path]:
    """This machine's recorded key, if the record still resolves.

    Both halves are checked. A record whose file has since been replaced or
    removed names a key this machine can no longer offer, and one the account
    no longer lists names a key the edge will refuse.
    """
    recorded = local_key(env)
    if not recorded:
        return None
    path = Path(recorded["path"])
    if fingerprint_for_file(path) != recorded["fingerprint"]:
        return None
    if not any(key.get("fingerprint") == recorded["fingerprint"] for key in registered):
        return None
    return path


def select_local_key(env: str, registered: List[dict]) -> Optional[Path]:
    """The key this machine should offer, or None when it cannot be chosen.

    Adopting is persistent, so it is done only where the choice is not a guess:
    a single match, or the client's own generated key among several. Every
    registered key authenticates equally — the edge resolves a connection
    against the whole account (`ssh-auth/resolve.go`) — so a tie including the
    generated key has an answer rather than a question, and picking it binds
    the machine to the key this client owns instead of one the user curates
    for other hosts. A tie among the user's own keys is still theirs to settle.
    """
    path = _recorded_key(env, registered)
    if path is not None:
        return path

    matches = recover(registered)
    generated = generated_public_key()
    if len(matches) == 1:
        chosen = matches[0]
    elif generated in matches:
        chosen = generated
    else:
        return None
    remember(env, fingerprint_for_file(chosen), chosen)
    return chosen


def resolve_local_key(env: str, registered: List[dict]) -> Path:
    """The key this machine should offer, or an error naming how to settle it.

    Exactly one key may be offered, so a choice this client cannot make is
    refused here rather than handed to ssh to try in turn.
    """
    chosen = select_local_key(env, registered)
    if chosen is not None:
        return chosen

    matches = recover(registered)
    if not matches:
        raise FreepodError(
            "no registered SSH key is available on this machine. "
            "Register one with `freepod key add`."
        )
    listed = "\n  ".join(str(p) for p in matches)
    raise FreepodError(
        "several local keys are registered on this account; name the one to "
        f"use with `freepod key add <path>`:\n  {listed}"
    )


# --------------------------------------------------------------------------
# The platform collection
# --------------------------------------------------------------------------


def _base(user_id: int) -> str:
    return f"/api/users/{user_id}/ssh-keys"


def list_keys(api: ApiClient, user_id: int) -> List[dict]:
    body = api.get_json(_base(user_id))
    if not isinstance(body, list):
        raise FreepodError(f"unexpected ssh-keys response: {body!r}")
    return body


def add_key(api: ApiClient, user_id: int, public_key: str, label: Optional[str]) -> dict:
    payload: Dict[str, Any] = {"public_key": public_key}
    if label:
        payload["label"] = label
    response = api.post(_base(user_id), json=payload)
    if not response.is_success:
        raise _refusal(response)
    return response.json()


def remove_key(api: ApiClient, user_id: int, fingerprint: str) -> None:
    from urllib.parse import quote

    response = api.delete(f"{_base(user_id)}/{quote(fingerprint, safe='')}")
    if not response.is_success:
        raise _refusal(response)


def _refusal(response) -> FreepodError:
    """The platform's own words, which already name the failing check.

    A duplicate is given its own class: the account already holding the key is
    the state the caller wanted, so it is the one refusal a caller can act on
    rather than report.
    """
    detail = ""
    code = ""
    try:
        body = response.json()
        if isinstance(body, dict):
            detail = body.get("detail") or ""
            code = body.get("code") or ""
    except ValueError:
        detail = response.text.strip()[:300]
    message = detail or f"the platform refused the request: HTTP {response.status_code}"
    if response.status_code == 409 and code == "duplicate_key":
        return DuplicateKey(message)
    return FreepodError(message)


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------


def render_table(keys: List[dict], local_fingerprint: Optional[str]) -> str:
    rows = []
    for key in keys:
        here = "*" if key.get("fingerprint") == local_fingerprint else BLANK
        rows.append(
            (
                here,
                key.get("fingerprint") or BLANK,
                key.get("label") or BLANK,
                key.get("key_type") or BLANK,
                format_time(key.get("created_at")),
            )
        )
    return render([COLUMNS, *rows]) if rows else ""
