"""Render the `freepod` click tree to developers/cli-reference.md.

    uv run --project ../../cli python scripts/cli_reference.py          write the page
    uv run --project ../../cli python scripts/cli_reference.py --check  fail if it is stale

Renders what `--help` shows: hidden commands and options are skipped, and help
text stops at click's `\\f` marker.
"""

import inspect
import sys
from pathlib import Path

import click

from freepod.cli import cli

OUTPUT = Path(__file__).resolve().parent.parent / "developers" / "cli-reference.md"

HEADER = """\
---
sidebar_position: 100
title: CLI reference
---

<!-- Generated by scripts/cli_reference.py from the freepod CLI. Do not edit. -->

# CLI reference

Every command accepts `-h` / `--help`.
"""


def help_text(command: click.Command) -> str:
    text = inspect.cleandoc(command.help or "").split("\f", 1)[0].strip()
    paragraphs = []
    for para in text.split("\n\n"):
        lines = para.split("\n")
        # click's `\b` marks a block it prints unwrapped: examples, mostly.
        if lines[0].strip() == "\b":
            paragraphs.append("\n".join(["```", inspect.cleandoc("\n".join(lines[1:])), "```"]))
        else:
            paragraphs.append(para)
    return "\n\n".join(paragraphs)


def cell(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def options_table(command: click.Command, ctx: click.Context) -> list[str]:
    rows = []
    for param in command.get_params(ctx):
        if not isinstance(param, click.Option) or param.hidden:
            continue
        record = param.get_help_record(ctx)
        if record is None or "--help" in param.opts:
            continue
        decl, desc = record
        rows.append(f"| `{cell(decl)}` | {cell(desc)} |")
    if not rows:
        return []
    return ["| Option | Description |", "| --- | --- |", *rows, ""]


def render(command: click.Command, ctx: click.Context, level: int, out: list[str]) -> None:
    out += [f"{'#' * level} `{ctx.command_path}`", ""]
    out += ["```", " ".join(command.collect_usage_pieces(ctx)).join([f"{ctx.command_path} ", ""]).strip(), "```", ""]
    text = help_text(command)
    if text:
        out += [text, ""]
    out += options_table(command, ctx)
    if isinstance(command, click.Group):
        for name in command.list_commands(ctx):
            sub = command.get_command(ctx, name)
            if sub is None or sub.hidden:
                continue
            render(sub, click.Context(sub, info_name=name, parent=ctx), level + 1, out)


def build() -> str:
    root = click.Context(cli, info_name="freepod")
    out = [HEADER]
    out += ["## Global options", "", "These go before the command: `freepod --verbose deploy`.", ""]
    out += options_table(cli, root)
    for name in cli.list_commands(root):
        sub = cli.get_command(root, name)
        if sub is None or sub.hidden:
            continue
        render(sub, click.Context(sub, info_name=name, parent=root), 2, out)
    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    page = build()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != page:
            print(f"{OUTPUT.name} is stale: run `npm run cli:reference` in ui/docs", file=sys.stderr)
            return 1
        print("cli reference ok")
        return 0
    OUTPUT.write_text(page)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
