{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "matrix.fullname" . }}
  labels:
    {{- include "matrix.labels" . | nindent 4 }}
  {{- $tlsCustom := and .Values.caelus.ingress.enabled (not .Values.caelus.ingress.tls.wildcard) }}
  {{- $annotations := merge (dict) (.Values.ingress.annotations | default dict) }}
  {{- if $tlsCustom }}{{- $_ := set $annotations "cert-manager.io/cluster-issuer" .Values.caelus.ingress.tls.issuer }}{{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- if $tlsCustom }}
  tls:
    - hosts:
        - {{ .Values.caelus.ingress.host | quote }}
      secretName: {{ .Values.caelus.ingress.tls.secretName | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.serverName | quote }}
      http:
        paths:
          - path: /_matrix
            pathType: Prefix
            backend:
              service:
                name: {{ include "matrix.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /_tuwunel
            pathType: Prefix
            backend:
              service:
                name: {{ include "matrix.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /.well-known/matrix
            pathType: Prefix
            backend:
              service:
                name: {{ include "matrix.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                {{- if .Values.elementWeb.enabled }}
                name: {{ include "matrix.elementWeb.fullname" . }}
                port:
                  number: 80
                {{- else }}
                name: {{ include "matrix.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
                {{- end }}
{{- end }}
