apiVersion: v1
kind: Service
metadata:
  name: {{ include "mattermost.postgresql.fullname" . }}
  labels:
    app: postgresql
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgresql
  selector:
    app: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mattermost.postgresql.fullname" . }}
  labels:
    app: postgresql
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mattermost.postgresql.fullname" . }}
  labels:
    app: postgresql
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  serviceName: {{ include "mattermost.postgresql.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: postgresql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}:{{ .Values.postgresql.imageTag }}
          ports:
            - containerPort: 5432
              name: postgresql
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mattermost.postgresql.fullname" . }}
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql
          {{- with .Values.postgresql.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.size }}