import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  developers: [
    { type: 'autogenerated', dirName: '.' },
    { type: 'link', label: 'Getting help', href: '/apps/getting-help' },
  ],
}

export default sidebars
